name: Pre-commit checks

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action source
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.0
